example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

m7011e/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('webstore.urls')),
    path('admin/', admin.site.urls),
]

webstore/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.admin.views.decorators import staff_member_required

from .views import home, about_us, Register, CreateProduct, ProductDetailView, profile, add_to_cart, cart_summary, delete_from_cart, product_list, ProfileUpdate, get_categories, category_product_list, category_detail, sub_category, sub_category_detail, order, change_password

app_name = 'webstore'

urlpatterns = [
    path('', home, name = 'home'),
    path('about-us', about_us, name = 'about_us'),

    # Cart
    path('cart/', cart_summary, name="cart"),
    path('cart/add/<int:product_id>/', add_to_cart, name="add_to_cart"),
    path('cart/delete/<int:product_id>', delete_from_cart, name="delete_item"),

    # Order
    path('order/', order, name="order"),

    # Products
    path('product/', product_list, name="product_list"),
    path('product/<int:pk>/', ProductDetailView.as_view(extra_context={'categories': get_categories()}), name='product_detail'),   

    # Category
    path('category/', category_product_list, name="categories"),
    path('category/<int:category_id>', category_detail, name='category_details'),
    path('category/subcategory/', sub_category, name='sub-category'),
    path('category/subcategory/<int:sub_category_id>', sub_category_detail, name='sub_category_details'),

    # Authorization
    path('register/', Register.as_view(), name = 'register'),
    path('login/', LoginView.as_view(template_name='pages/login.html', extra_context={'categories': get_categories()}), name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('profile/update/', ProfileUpdate.as_view(), name='profile_update'),
    path('profile/change-password/', change_password, name='change_password'),
    
    # Admin
    path('product/create/', staff_member_required(CreateProduct.as_view()), name='create_product'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webstore/models.py
from django.db import models

# Create your models here.

webstore/models/cart_product.py
from django.db import models
from typing import Literal
from django.contrib.auth import get_user_model
from .product import Product

class CartProduct(models.Model):
    user: models.ForeignKey = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity: models.IntegerField = models.IntegerField(default=1)

    class Meta:
        unique_together: tuple[Literal['user_id'], Literal['product_id']] = ('user_id', 'product_id')

webstore/models/categories.py
from django.db import models

class Categories(models.Model):
    name: models.TextField = models.TextField(max_length=255)
    image: models.ImageField = models.ImageField(blank=True, null=True)

    def __str__(self)-> models.TextField:
        return self.name

webstore/models/category.py
from django.db import models

class Category(models.Model):
    name: models.TextField = models.TextField(max_length=255)
    image: models.ImageField = models.ImageField(blank=True, null=True)

    def __str__(self)-> models.TextField:
        return self.name

webstore/models/in_categorie.py
from django.db import models
from typing import Literal
from .product import Product
from .category import Category

class InCategorie(models.Model):
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    category: models.ForeignKey = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together: tuple[Literal['product'], Literal['category']] = ('product', 'category')

webstore/models/in_category.py
from django.db import models
from typing import Literal
from .product import Product
from .category import Category

class InCategory(models.Model):
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    category: models.ForeignKey = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together: tuple[Literal['product'], Literal['category']] = ('product', 'category')

webstore/models/in_subcategory.py
from django.db import models
from typing import Literal
from .product import Product
from .subcategory import Subcategory

class InSubcategory(models.Model):
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    subcategory: models.ForeignKey = models.ForeignKey(Subcategory, on_delete=models.CASCADE)

    class Meta:
        unique_together: tuple[Literal['product'], Literal['subcategory']] = ('product', 'subcategory')

webstore/models/order.py
from django.db import models
from django.contrib.auth import get_user_model
from typing import Literal

class Order(models.Model):
    PROCESSING: Literal['PS'] = 'PS'
    PACKAGING: Literal['PG'] = 'PG'
    SHIPPING: Literal['SH'] = 'SH'
    PICKUP: Literal['PU'] = 'PU'
    DELIVERED: Literal['DV'] = 'DV'

    STATUS: list[tuple] = [
        (PROCESSING, 'Processing'),
        (PACKAGING, 'Packaging'),
        (SHIPPING, 'Shipping'),
        (PICKUP, 'Pickup'),
        (DELIVERED, 'Delivered'),
    ]

    order_date: models.DateTimeField = models.DateTimeField()
    customer: models.ForeignKey = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    address: models.TextField = models.TextField()
    status: models.CharField = models.CharField(
        max_length=2,
        choices=STATUS,
        default=PROCESSING,
    )
    delivery: models.DateTimeField = models.DateTimeField(blank=True, null=True)

webstore/models/order_product.py
from django.db import models
from typing import Literal
from .order import Order
from .product import Product

class OrderProduct(models.Model):
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    order: models.ForeignKey = models.ForeignKey(Order, on_delete=models.DO_NOTHING)
    quantity: models.IntegerField = models.IntegerField(default=1)
    price: models.DecimalField = models.DecimalField(decimal_places=2, max_digits=16)
    
    class Meta:
        unique_together: tuple[Literal['product_id'], Literal['order_id']] = ('product_id', 'order_id')

webstore/models/orders.py
from django.db import models
from django.contrib.auth import get_user_model
from typing import Literal

class Orders(models.Model):
    PROCESSING: Literal['PS'] = 'PS'
    PACKAGING: Literal['PG'] = 'PG'
    SHIPPING: Literal['SH'] = 'SH'
    PICKUP: Literal['PU'] = 'PU'
    DELIVERED: Literal['DV'] = 'DV'

    STATUS: list[tuple] = [
        (PROCESSING, 'Processing'),
        (PACKAGING, 'Packaging'),
        (SHIPPING, 'Shipping'),
        (PICKUP, 'Pickup'),
        (DELIVERED, 'Delivered'),
    ]

    order_date: models.DateTimeField = models.DateTimeField()
    customer: models.ForeignKey = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    address: models.TextField = models.TextField()
    status: models.CharField = models.CharField(
        max_length=2,
        choices=STATUS,
        default=PROCESSING,
    )
    delivery: models.DateTimeField = models.DateTimeField(blank=True, null=True)

webstore/models/product.py
from django.db import models

class Product(models.Model):
    name: models.TextField = models.TextField(max_length=255)
    description: models.TextField = models.TextField(blank=True, null=True)
    price: models.DecimalField = models.DecimalField(decimal_places=2, max_digits=16)
    stock: models.IntegerField = models.IntegerField(default=0)
    thumbnail: models.ImageField = models.ImageField(blank=True, null=True)

    def __str__(self) -> models.TextField:
        return self.name

webstore/models/products.py
from django.db import models

class Products(models.Model):
    name: models.TextField = models.TextField(max_length=255)
    description: models.TextField = models.TextField(blank=True, null=True)
    price: models.DecimalField = models.DecimalField(decimal_places=2, max_digits=16)
    stock: models.IntegerField = models.IntegerField(default=0)
    thumbnail: models.ImageField = models.ImageField(blank=True, null=True)

    def __str__(self) -> models.TextField:
        return self.name

webstore/models/review.py
from django.db import models
from django.contrib.auth import get_user_model
from .product import Product

class Review(models.Model):
    user: models.ForeignKey = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating: models.IntegerField = models.IntegerField()
    text: models.TextField = models.TextField(blank=True)
    create_time: models.DateTimeField = models.DateTimeField()

webstore/models/subcategories.py
from django.db import models
from .categories import Categories

class Subcategories(models.Model):
    category: models.ForeignKey = models.ForeignKey(Categories, on_delete=models.CASCADE)
    name: models.TextField = models.TextField(max_length=255)
    image: models.ImageField = models.ImageField(blank=True)

    def __str__(self) -> models.TextField:
        return self.name

webstore/models/subcategory.py
from django.db import models
from .category import Category

class Subcategory(models.Model):
    category: models.ForeignKey = models.ForeignKey(Category, on_delete=models.CASCADE)
    name: models.TextField = models.TextField(max_length=255)
    image: models.ImageField = models.ImageField(blank=True)

    def __str__(self) -> models.TextField:
        return self.name

webstore/models/user_profile.py
from django.db import models
from django.contrib.auth import get_user_model
from typing import Literal

class UserProfile(models.Model):
    CUSTOMER: Literal['CM'] = 'CM'
    ADMIN:  Literal['AD'] = 'AD'
    SUPERUSER: Literal['SU'] = 'SU'
    
    ROLE: list[tuple] = [
        (CUSTOMER, 'Customer'),
        (ADMIN, 'Admin'),
        (SUPERUSER, 'Superuser'),
    ]
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='profile'
        )
    role: models.CharField = models.CharField(
        max_length=2,
        choices=ROLE,
        default=CUSTOMER,
    )

    class Meta:
        verbose_name_plural = 'UserProfiles'
        db_table = 'user_profile'

    def __str__(self):
        return self.user.get_username()

webstore/models/user_profiles.py
from django.db import models
from django.contrib.auth import get_user_model
from typing import Literal
import datetime

class UserProfiles(models.Model):
    CUSTOMER: Literal['CM'] = 'CM'
    ADMIN:  Literal['AD'] = 'AD'
    SUPERUSER: Literal['SU'] = 'SU'
    
    ROLE: list[tuple] = [
        (CUSTOMER, 'Customer'),
        (ADMIN, 'Admin'),
        (SUPERUSER, 'Superuser'),
    ]
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    role: models.CharField = models.CharField(
        max_length=2,
        choices=ROLE,
        default=CUSTOMER,
    )

    def __str__(self):
        return self.role

webstore/models/users.py
from django.db import models
from typing import Literal
import datetime

class Users(models.Model):
    CUSTOMER: Literal['CM'] = 'CM'
    ADMIN:  Literal['AD'] = 'AD'
    SUPERUSER: Literal['SU'] = 'SU'
    
    ROLE: list[tuple] = [
        (CUSTOMER, 'Customer'),
        (ADMIN, 'Admin'),
        (SUPERUSER, 'Superuser'),
    ]
    email: models.EmailField = models.EmailField(unique=True)
    create_time: models.DateTimeField = models.DateTimeField()
    role: models.CharField = models.CharField(
        max_length=2,
        choices=ROLE,
        default=CUSTOMER,
    )

    def __str__(self) -> models.EmailField:
        return self.email

webstore/models/video.py
from django.db import models

from embed_video.fields import EmbedVideoField

class Video(models.Model):
    title = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True)
    url = EmbedVideoField()

    def __str__(self) -> str:
        return str(self.title)

    class Meta:
        ordering = ['-added']

webstore/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from webstore.models import UserProfile, Product

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'password1', 'password2')
        error_messages = {
            'username': {
                'unique': "That user name is already in use",
            }
        }

        def save(self, commit=True):
            """
            Verifies that the given data is valid then saves the new user into the db.
            """
            user = super(NewUserForm, self).save(commit=False)
            user.email = self.cleaned_data['email']
            if commit:
                user.save()
                UserProfile.objects.create(user=user)
            return user

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'stock', 'thumbnail']

class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username', )

webstore/templates/includes/_menu.html
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'webstore:home' %}">Webstore</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
              aria-controls="navbarCollapse" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse" style="">
        
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'webstore:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webstore:about_us' %}">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webstore:product_list' %}">Products</a>
          </li>

          <li class="dropdown nav-item">
            <a class="dropdown-toggle nav-link" href="#" id="multilevelDropdownMenu1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
            <ul class="dropdown-menu" aria-labelledby="multilevelDropdownMenu1">
                {% for key, value in categories.items %}
                {% if value %}
                <li class="dropdown dropend">
                  <a class="dropdown-item dropdown-toggle" href="{% url 'webstore:category_details' key.id %}" id="multilevelDropdownMenu1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{key}}</a>
                  <ul class="dropdown-menu" aria-labelledby="multilevelDropdownMenu2">
                      {% for x in value %}
                      <li><a class="dropdown-item" href="{% url 'webstore:sub_category_details' x.id %}">{{x}}</a></li>
                      {% endfor %}
                  </ul>
                </li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'webstore:category_details' key.id %}">{{key}}</a></li>
                {% endif %}
                {% endfor %}
            </ul>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'webstore:sub-category' %}">Sub Categories</a>
        </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'webstore:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'webstore:cart' %}">Cart</a>
            </li>
          {% endif %}


          <!-- Right Side -->
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'webstore:logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'webstore:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'webstore:register' %}">Register</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <script>
    let dropdowns = document.querySelectorAll('.dropdown-toggle')
    dropdowns.forEach((dd)=>{
        dd.addEventListener('click', function (e) {
            var el = this.nextElementSibling
            el.style.display = el.style.display==='block'?'none':'block'
        })
        dd.addEventListener('click', function (e) {
            var el = this.nextElementSibling
            el.style.display = el.style.display==='block'?'block':'none'
        })
    })
  </script>