example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

m7011e/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('webstore.urls')),
    path('admin/', admin.site.urls),
]

webstore/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.admin.views.decorators import staff_member_required

from .views import home, about_us, Register, CreateProduct, ProductDetailView, profile, add_to_cart, cart_summary, delete_from_cart, product_list, ProfileUpdate, get_categories, category_product_list, category_detail, sub_category, sub_category_detail, order, change_password

app_name = 'webstore'

urlpatterns = [
    path('', home, name = 'home'),
    path('about-us', about_us, name = 'about_us'),

    # Cart
    path('cart/', cart_summary, name="cart"),
    path('cart/add/<int:product_id>/', add_to_cart, name="add_to_cart"),
    path('cart/delete/<int:product_id>', delete_from_cart, name="delete_item"),

    # Order
    path('order/', order, name="order"),

    # Products
    path('product/', product_list, name="product_list"),
    path('product/<int:pk>/', ProductDetailView.as_view(extra_context={'categories': get_categories()}), name='product_detail'),   

    # Category
    path('category/', category_product_list, name="categories"),
    path('category/<int:category_id>', category_detail, name='category_details'),
    path('category/subcategory/', sub_category, name='sub-category'),
    path('category/subcategory/<int:sub_category_id>', sub_category_detail, name='sub_category_details'),

    # Authorization
    path('register/', Register.as_view(), name = 'register'),
    path('login/', LoginView.as_view(template_name='pages/login.html', extra_context={'categories': get_categories()}), name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('profile/update/', ProfileUpdate.as_view(), name='profile_update'),
    path('profile/change-password/', change_password, name='change_password'),
    
    # Admin
    path('product/create/', staff_member_required(CreateProduct.as_view()), name='create_product'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webstore/models.py
from django.db import models

# Create your models here.

webstore/models/cart_product.py
from django.db import models
from typing import Literal
from django.contrib.auth import get_user_model
from .product import Product

class CartProduct(models.Model):
    user: models.ForeignKey = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity: models.IntegerField = models.IntegerField(default=1)

    class Meta:
        unique_together: tuple[Literal['user_id'], Literal['product_id']] = ('user_id', 'product_id')

webstore/models/categories.py
from django.db import models

class Categories(models.Model):
    name: models.TextField = models.TextField(max_length=255)
    image: models.ImageField = models.ImageField(blank=True, null=True)

    def __str__(self)-> models.TextField:
        return self.name

webstore/models/category.py
from django.db import models

class Category(models.Model):
    name: models.TextField = models.TextField(max_length=255)
    image: models.ImageField = models.ImageField(blank=True, null=True)

    def __str__(self)-> models.TextField:
        return self.name

webstore/models/in_categorie.py
from django.db import models
from typing import Literal
from .product import Product
from .category import Category

class InCategorie(models.Model):
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    category: models.ForeignKey = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together: tuple[Literal['product'], Literal['category']] = ('product', 'category')

webstore/models/in_category.py
from django.db import models
from typing import Literal
from .product import Product
from .category import Category

class InCategory(models.Model):
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    category: models.ForeignKey = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together: tuple[Literal['product'], Literal['category']] = ('product', 'category')

webstore/models/in_subcategory.py
from django.db import models
from typing import Literal
from .product import Product
from .subcategory import Subcategory

class InSubcategory(models.Model):
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    subcategory: models.ForeignKey = models.ForeignKey(Subcategory, on_delete=models.CASCADE)

    class Meta:
        unique_together: tuple[Literal['product'], Literal['subcategory']] = ('product', 'subcategory')

webstore/models/order.py
from django.db import models
from django.contrib.auth import get_user_model
from typing import Literal

class Order(models.Model):
    PROCESSING: Literal['PS'] = 'PS'
    PACKAGING: Literal['PG'] = 'PG'
    SHIPPING: Literal['SH'] = 'SH'
    PICKUP: Literal['PU'] = 'PU'
    DELIVERED: Literal['DV'] = 'DV'

    STATUS: list[tuple] = [
        (PROCESSING, 'Processing'),
        (PACKAGING, 'Packaging'),
        (SHIPPING, 'Shipping'),
        (PICKUP, 'Pickup'),
        (DELIVERED, 'Delivered'),
    ]

    order_date: models.DateTimeField = models.DateTimeField()
    customer: models.ForeignKey = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    address: models.TextField = models.TextField()
    status: models.CharField = models.CharField(
        max_length=2,
        choices=STATUS,
        default=PROCESSING,
    )
    delivery: models.DateTimeField = models.DateTimeField(blank=True, null=True)

webstore/models/order_product.py
from django.db import models
from typing import Literal
from .order import Order
from .product import Product

class OrderProduct(models.Model):
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    order: models.ForeignKey = models.ForeignKey(Order, on_delete=models.DO_NOTHING)
    quantity: models.IntegerField = models.IntegerField(default=1)
    price: models.DecimalField = models.DecimalField(decimal_places=2, max_digits=16)
    
    class Meta:
        unique_together: tuple[Literal['product_id'], Literal['order_id']] = ('product_id', 'order_id')

webstore/models/orders.py
from django.db import models
from django.contrib.auth import get_user_model
from typing import Literal

class Orders(models.Model):
    PROCESSING: Literal['PS'] = 'PS'
    PACKAGING: Literal['PG'] = 'PG'
    SHIPPING: Literal['SH'] = 'SH'
    PICKUP: Literal['PU'] = 'PU'
    DELIVERED: Literal['DV'] = 'DV'

    STATUS: list[tuple] = [
        (PROCESSING, 'Processing'),
        (PACKAGING, 'Packaging'),
        (SHIPPING, 'Shipping'),
        (PICKUP, 'Pickup'),
        (DELIVERED, 'Delivered'),
    ]

    order_date: models.DateTimeField = models.DateTimeField()
    customer: models.ForeignKey = models.ForeignKey(get_user_model(), on_delete=models.DO_NOTHING)
    address: models.TextField = models.TextField()
    status: models.CharField = models.CharField(
        max_length=2,
        choices=STATUS,
        default=PROCESSING,
    )
    delivery: models.DateTimeField = models.DateTimeField(blank=True, null=True)

webstore/models/product.py
from django.db import models

class Product(models.Model):
    name: models.TextField = models.TextField(max_length=255)
    description: models.TextField = models.TextField(blank=True, null=True)
    price: models.DecimalField = models.DecimalField(decimal_places=2, max_digits=16)
    stock: models.IntegerField = models.IntegerField(default=0)
    thumbnail: models.ImageField = models.ImageField(blank=True, null=True)

    def __str__(self) -> models.TextField:
        return self.name

webstore/models/products.py
from django.db import models

class Products(models.Model):
    name: models.TextField = models.TextField(max_length=255)
    description: models.TextField = models.TextField(blank=True, null=True)
    price: models.DecimalField = models.DecimalField(decimal_places=2, max_digits=16)
    stock: models.IntegerField = models.IntegerField(default=0)
    thumbnail: models.ImageField = models.ImageField(blank=True, null=True)

    def __str__(self) -> models.TextField:
        return self.name

webstore/models/review.py
from django.db import models
from django.contrib.auth import get_user_model
from .product import Product

class Review(models.Model):
    user: models.ForeignKey = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product: models.ForeignKey = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating: models.IntegerField = models.IntegerField()
    text: models.TextField = models.TextField(blank=True)
    create_time: models.DateTimeField = models.DateTimeField()

webstore/models/subcategories.py
from django.db import models
from .categories import Categories

class Subcategories(models.Model):
    category: models.ForeignKey = models.ForeignKey(Categories, on_delete=models.CASCADE)
    name: models.TextField = models.TextField(max_length=255)
    image: models.ImageField = models.ImageField(blank=True)

    def __str__(self) -> models.TextField:
        return self.name

webstore/models/subcategory.py
from django.db import models
from .category import Category

class Subcategory(models.Model):
    category: models.ForeignKey = models.ForeignKey(Category, on_delete=models.CASCADE)
    name: models.TextField = models.TextField(max_length=255)
    image: models.ImageField = models.ImageField(blank=True)

    def __str__(self) -> models.TextField:
        return self.name

webstore/models/user_profile.py
from django.db import models
from django.contrib.auth import get_user_model
from typing import Literal

class UserProfile(models.Model):
    CUSTOMER: Literal['CM'] = 'CM'
    ADMIN:  Literal['AD'] = 'AD'
    SUPERUSER: Literal['SU'] = 'SU'
    
    ROLE: list[tuple] = [
        (CUSTOMER, 'Customer'),
        (ADMIN, 'Admin'),
        (SUPERUSER, 'Superuser'),
    ]
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='profile'
        )
    role: models.CharField = models.CharField(
        max_length=2,
        choices=ROLE,
        default=CUSTOMER,
    )

    class Meta:
        verbose_name_plural = 'UserProfiles'
        db_table = 'user_profile'

    def __str__(self):
        return self.user.get_username()

webstore/models/user_profiles.py
from django.db import models
from django.contrib.auth import get_user_model
from typing import Literal
import datetime

class UserProfiles(models.Model):
    CUSTOMER: Literal['CM'] = 'CM'
    ADMIN:  Literal['AD'] = 'AD'
    SUPERUSER: Literal['SU'] = 'SU'
    
    ROLE: list[tuple] = [
        (CUSTOMER, 'Customer'),
        (ADMIN, 'Admin'),
        (SUPERUSER, 'Superuser'),
    ]
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    role: models.CharField = models.CharField(
        max_length=2,
        choices=ROLE,
        default=CUSTOMER,
    )

    def __str__(self):
        return self.role

webstore/models/users.py
from django.db import models
from typing import Literal
import datetime

class Users(models.Model):
    CUSTOMER: Literal['CM'] = 'CM'
    ADMIN:  Literal['AD'] = 'AD'
    SUPERUSER: Literal['SU'] = 'SU'
    
    ROLE: list[tuple] = [
        (CUSTOMER, 'Customer'),
        (ADMIN, 'Admin'),
        (SUPERUSER, 'Superuser'),
    ]
    email: models.EmailField = models.EmailField(unique=True)
    create_time: models.DateTimeField = models.DateTimeField()
    role: models.CharField = models.CharField(
        max_length=2,
        choices=ROLE,
        default=CUSTOMER,
    )

    def __str__(self) -> models.EmailField:
        return self.email

webstore/models/video.py
from django.db import models

from embed_video.fields import EmbedVideoField

class Video(models.Model):
    title = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now_add=True)
    url = EmbedVideoField()

    def __str__(self) -> str:
        return str(self.title)

    class Meta:
        ordering = ['-added']

webstore/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from webstore.models import UserProfile, Product

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'password1', 'password2')
        error_messages = {
            'username': {
                'unique': "That user name is already in use",
            }
        }

        def save(self, commit=True):
            """
            Verifies that the given data is valid then saves the new user into the db.
            """
            user = super(NewUserForm, self).save(commit=False)
            user.email = self.cleaned_data['email']
            if commit:
                user.save()
                UserProfile.objects.create(user=user)
            return user

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'stock', 'thumbnail']

class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username', )

webstore/templates/pages/about_us.html
{% extends 'layouts/public_base.html' %}
{% load embed_video_tags %}
{% load static %}

{% block content %}
<section class="py-5 text-center">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">About Us</h1>
        <p class="lead text-muted">A little bit about us!</p>
        <p>
          <a href="{% url 'webstore:home' %}" class="btn btn-primary my-2">Home</a>
        </p>
      </div>
    </div>
  </section>

  <h1 class="mb-5">Videos</h1>
  <div class="d-flex flex-wrap">
  {% for item in videos %}
    <div class="px-3 mb-5">
    {% video item.url '426x240' %}
    <div class ="d-flex justify-content-start">{{ item.title }}</div>
    </div >
  {% endfor %}
  </div>
{% endblock %}

webstore/templates/pages/category_detail.html
{% extends 'layouts/public_base.html' %}
{% load static %}
{% block description %}
  Login page.
{% endblock %}

{% block keywords %}
  login
{% endblock %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content %}

<section class="py-5 text-center">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Categories Detail</h1>
        <p class="lead text-muted">Detail of the Category!</p>
        <p>
          <a href="{% url 'webstore:categories' %}" class="btn btn-primary my-2">Categories</a>
        </p>
      </div>
    </div>
  </section>
{% if subcategories%}
<hr>
<div class="row py-lg-5">
<h1 class="fw-light">Sub Categories</h1>
</div>
{% for row in subcategories %}
  <div class="row mx-n2 mx-sm-n3">
    {% for cat in row %}
    <div class="col-6 col-lg-3 px-2 px-sm-3 mb-3 mb-sm-5">
      <!-- Product -->
      <div class="card text-center h-100">
        <div class="position-relative">
          <a class="text-secondary" href="{% url 'webstore:category_details' cat.id %}">
              <img class="card-img-top" src="{{ cat.image.url }}" alt="Image Description">
          </a>
        </div>
    
        <div class="card-body pt-4 px-4 pb-0">
          <div class="mb-2">
            <h4 class="font-size-1 font-weight-normal">
              <a class="text-secondary" href="{% url 'webstore:category_details' cat.id %}">{{cat.name}}</a>
            </h4>
          </div>
        </div>
    
      </div>
      <!-- End Product -->
    </div>
    {% endfor %}
    </div>
    <!-- End Products -->
    {% endfor %}
{% endif %}

{% if products %}
<hr>
<div class="row py-lg-5">
    <h1 class="fw-light">Products in Category</h1>
    </div>
{% for row in products %}
<div class="row mx-n2 mx-sm-n3">
  {% for product in row %}
  <div class="col-6 col-lg-3 px-2 px-sm-3 mb-3 mb-sm-5">
    <!-- Product -->
    <div class="card text-center h-100">
      <div class="position-relative">
        <a class="text-secondary" href="{% url 'webstore:product_detail' product.2 %}">
          <img class="card-img-top" src="{{ product.0 }}" alt="Image Description">
        </a>
      </div>
  
      <div class="card-body pt-4 px-4 pb-0">
        <div class="mb-2">
          <a class="d-inline-block text-secondary small font-weight-medium mb-1" href="{% url 'webstore:category_details' product.1.category.id %}">{{product.1.category.name}}</a>
          <h4 class="font-size-1 font-weight-normal">
            <a class="text-secondary" href="{% url 'webstore:product_detail' product.2 %}">{{product.3}}</a>
          </h4>
          <div class="d-block">
            <span class="font-weight-medium">${{product.4}}</span>
          </div>
          <div class="d-block">
            <span class="font-weight-medium">Stock: {{product.5}}</span>
          </div>
        </div>
      </div>
  
      <div class="card-footer border-0 pt-0 pb-4 px-4">
        <div class="mb-3">
          <a class="d-inline-flex align-items-center small" href="#"> 
            <div class="text-warning mr-2">
              <small class="fas fa-star"></small>
              <small class="fas fa-star"></small>
              <small class="fas fa-star"></small>
              <small class="fas fa-star"></small>
              <small class="fas fa-star"></small>
            </div>
            <span class="text-secondary">9</span>
          </a>
        </div>
        <a href="{% url 'webstore:add_to_cart' product.2 %}" type="button" class="btn btn-sm btn-outline-primary btn-sm-wide btn-pill transition-3d-hover">Add to Cart</a>
      </div>
    </div>
    <!-- End Product -->
  </div>
  {% endfor %}
  </div>
  <!-- End Products -->
  {% endfor %}
{% endif %}

 {% endblock %}
 

webstore/templates/pages/home.html
{% extends 'layouts/public_base.html' %}
{% load static %}

{% block content %}

  <section class="py-5 text-center">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Home Page</h1>
        <p class="lead text-muted">This is the home page...</p>
        <p>
          <a href="{% url 'webstore:categories' %}" class="btn btn-primary my-2">Categories</a>
          <a href="{% url 'webstore:product_list' %}" class="btn btn-secondary my-2">Products</a>
        </p>
      </div>
    </div>
  </section>  

{% endblock %}

webstore/templates/pages/login.html
<!--
  Based on the example login code from Sandeep Patil
-->

{% extends "layouts/public_base.html" %}

{% block content %}
  <div class="row py-5">
    <div class="col-xs-12">

      <!-- log in form -->
      <div class="form">
        <form method="post" action="{% url 'webstore:login' %}">
          {% csrf_token %}
          
          <div class="form-group">
            <label class="control-label" for="signin-username">Username</label>
            <input class="form-control" type="text" id="signin-username"
                    placeholder="Username" name="username"
                    value="{{ form.username.value|default_if_none:"" }}">
          </div>

          <div class="form-group">
            <label class="control-label"
                    for="signin-password">Password</label>
            <input class="form-control" type="password" placeholder="Password"
                    name="password">
          </div>
          {% if form.errors %}
            <div class="form-group has-error">
              <div class="control-label">
                <span>Your username and password didn't match. Please try again.</span>
              </div>
            </div>
          {% endif %}

          <div class="form-group">
            <input class="form-control btn btn-primary" type="submit"
                    value="Login">
          </div>
          <input type="hidden" name="next" value="{{ next }}"/>
        </form>

        <p class="message">Not registered? <a href="{% url 'webstore:register' %}">Create
          an account</a></p>
        <hr />
      </div>
    </div>
  </div>
{% endblock %}

webstore/templates/pages/product_detail.html
{% extends 'layouts/public_base.html' %}
{% load static %}

{% block content %}
  <!-- Product section-->
  <section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.thumbnail.url }}"/></div>
            <div class="col-md-6">
                {% for cat in category %}
                <a class="text-secondary" href="{% url 'webstore:category_details' cat.category.id %}">
                    <div class="small mb-1">{{cat.category.name}}</div>
                </a>
                {% endfor %}
                <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration">Stock: {{ product.stock }} - </span>
                    <span>${{ product.price }}</span>
                </div>
                <p class="lead">{{ product.description }}</p>
                <form method="post" action=" {% url 'webstore:add_to_cart' product.id  %} ">
                  {% csrf_token %}
                  <div class="d-flex">
                      <input name="quantity" class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                      <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                          <i class="bi-cart-fill me-1"></i>
                          Add to cart
                      </button>
                  </div>
              </form>
            </div>
        </div>
    </div>
</section>

<section class="py-5 text-center">
    <div class="col-lg-6 col-md-8 mx-auto">
      <p>
        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary my-2">Go Back!</a>
      </p>
    </div>
</section>

{% endblock %}

webstore/templates/pages/profile.html
{% extends 'layouts/public_base.html' %}
{% load static %}
{% block description %}
  Login page.
{% endblock %}

{% block keywords %}
  login
{% endblock %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content %}

<section class="py-5 text-center">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Profile Page</h1>
      <p class="lead text-muted">Check out your information!</p>
    </div>
  </div>
</section>  
  
<div class="row py-5">
    <div class="col-xs-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Profile Details
            <a class="btn btn-warning btn-xs pull-right" href="{% url 'webstore:profile_update' %}"> 
              Update Profile
            </a>
            <a class="btn btn-warning btn-xs pull-right" href="{% url 'webstore:change_password' %}"> 
              Change Password
            </a>
          </h3>
          
        </div>
        <table class="table table-striped">
          <tbody>
            <tr>
                <td>
                  Username
                </td>
                <td>
                  {{ user.username }}
                </td>
              </tr>
              <tr>
                <td>
                  Email
                </td>
                <td>
                  {{ user.email }}
                </td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  
<section>
  <div class="row">
   <table class="table text-center">
     <tr class="text-center">
       <th>Order Number</th>
       <th>Date</th>
       <th>Price</th>
       <th>Status</th>

     </tr>
     {% if order %}
     {% for item in order %}
       <tr>
         <td><div class="asdasd">{{item.0}}
          <span class="tooltiptext">
            <table class="text-light table text-center">
              <tr class="text-light text-center">
                <td>Name</td>
                <td>Quantity</td>
                <td>Price</td>
              </tr>
              {% for prod in item.4 %}
              <tr class="text-light text-center">
                <td><a class="text-secondary" href="{% url 'webstore:product_detail' prod.product.id %}">{{prod.product.name}}</a></td>
                <td>{{prod.quantity}}</td>
                <td>{{prod.price}}</td>
              </tr>
              {% endfor %}
            </table>
          </span>
        </div></td>
         <td>
           {{ item.1 }}
         </td>
         <td>{{ item.2 }}</td>
         <td>{{ item.3 }}</td>
       </tr>
     {% empty %}
       <tr>
         <td colspan= 3> You have not added any items yet.</td>
       </tr>
     {% endfor %}
     <tr>
       {% if amount != None %}
       <td colspan=3>
         <strong class="pull-right">Order Total:</strong>
       </td>
       
       <td colspan= 1>
         <strong>${{ amount }}</strong>
       </td>
       {% endif %}
     </tr>
     {% endif %}
   </table>
    
  </div>
</section>


<style>
  .asdasd {
    position: relative;
    display: inline-block;
    border-bottom: 1px dotted black;
  }
  
  .asdasd .tooltiptext {
    visibility: hidden;
    background-color: black;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;
    position: absolute;
    z-index: 1;
    bottom: 100%;
    left: 50%;
    margin-left: -60px;
    
    /* Fade in tooltip - takes 1 second to go from 0% to 100% opac: */
    opacity: 0;
    transi  tion: opacity 1s;
  }
  
  .asdasd:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
  }

</style>

{% endblock %}

webstore/templates/pages/subcategory_detail.html
{% extends 'layouts/public_base.html' %}
{% load static %}
{% block description %}
  Login page.
{% endblock %}

{% block keywords %}
  login
{% endblock %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content %}

<section class="py-5 text-center">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Sub Categories Detail</h1>
        <p class="lead text-muted">Detail of the Sub Category!</p>
        <p>
          <a href="{% url 'webstore:sub-category' %}" class="btn btn-primary my-2">Sub Categories</a>
        </p>
      </div>
    </div>
  </section>

{% if products %}
<hr>
<div class="row py-lg-5">
    <h1 class="fw-light">Products in Sub Category</h1>
    </div>
{% for row in products %}
<div class="row mx-n2 mx-sm-n3">
  {% for product in row %}
  <div class="col-6 col-lg-3 px-2 px-sm-3 mb-3 mb-sm-5">
    <!-- Product -->
    <div class="card text-center h-100">
      <div class="position-relative">
        <a class="text-secondary" href="{% url 'webstore:product_detail' product.2 %}">
          <img class="card-img-top" src="{{ product.0 }}" alt="Image Description">
        </a>
      </div>
  
      <div class="card-body pt-4 px-4 pb-0">
        <div class="mb-2">
          <a class="d-inline-block text-secondary small font-weight-medium mb-1" href="{% url 'webstore:category_details' product.1.category.id %}">{{product.1.category.name}}</a>
          <h4 class="font-size-1 font-weight-normal">
            <a class="text-secondary" href="{% url 'webstore:product_detail' product.2 %}">{{product.3}}</a>
          </h4>
          <div class="d-block">
            <span class="font-weight-medium">${{product.4}}</span>
          </div>
          <div class="d-block">
            <span class="font-weight-medium">Stock: {{product.5}}</span>
          </div>
        </div>
      </div>
  
      <div class="card-footer border-0 pt-0 pb-4 px-4">
        <div class="mb-3">
          <a class="d-inline-flex align-items-center small" href="#"> 
            <div class="text-warning mr-2">
              <small class="fas fa-star"></small>
              <small class="fas fa-star"></small>
              <small class="fas fa-star"></small>
              <small class="fas fa-star"></small>
              <small class="fas fa-star"></small>
            </div>
            <span class="text-secondary">9</span>
          </a>
        </div>
        <a href="{% url 'webstore:add_to_cart' product.2 %}" type="button" class="btn btn-sm btn-outline-primary btn-sm-wide btn-pill transition-3d-hover">Add to Cart</a>
      </div>
    </div>
    <!-- End Product -->
  </div>
  {% endfor %}
  </div>
  <!-- End Products -->
  {% endfor %}
{% endif %}

 {% endblock %}
 